metadata.format.version = "1.1"

[versions]

minestom = "fc90fe8852"
tntloader = "ecda3972cb"

kotlin-coroutines = "1.6.4"

# Gradle plugins
blossom = "1.3.0"
shadowJar = "7.0.0"
oci-container = "3.3.0"

[libraries]

minestom = { group = "com.github.Minestom", name = "Minestom", version.ref = "minestom" }
tntloader = { group = "com.github.EmortalMC", name = "TNT", version.ref = "tntloader" }

kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" , version.ref = "kotlin-coroutines" }

[bundles]

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
oci-container = { id = "com.google.cloud.tools.jib", version.ref = "oci-container" }
